apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: AC Access Control, SC System and
      Communications Protection
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement, SC-28 Protection
      Of Information At Rest
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: validate-etcd-encryption
  namespace: default
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: enable-etcd-encryption
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: APIServer
            metadata:
              name: cluster
            spec:
              encryption:
                type: aescbc
        remediationAction: inform
        severity: low
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: enable-etcd-encryption-status-kubeapi
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.openshift.io/v1
            kind: KubeAPIServer
            metadata:
              name: cluster
            status:
              conditions:
              - message: 'All resources encrypted: secrets, configmaps'
                reason: EncryptionCompleted
        remediationAction: inform
        severity: low
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: validate-etcd-encryption-placement
  namespace: default
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: validate-etcd-encryption-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: validate-etcd-encryption
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: validate-etcd-encryption-placement
  namespace: default
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
